services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: payments_test

    ports:
      - "5432:5432"

    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --overprovisioned
      - --node-id=0
      - --kafka_client-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka_client-addr=PLAINTEXT://localhost:9092
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=localhost:8082
    ports:
      - "9092:9092"
      - "8082:8082"


  payments:
    build: app/services/payment_services   # собрать из Dockerfile в этой папке
    ports:
      - "8000:8000"
    depends_on:
      - postgres

