[pytest]
markers =
    kafka: тесты, работающие с Kafka/Redpanda (требуют поднятого брокера)
    llm: тесты с реальными вызовами LLM API (тратят токены)
testpaths = tests
addopts =
    -ra
    --strict-markers
#   -p no:randomly - не загружает плагин вообще. Тесты всегда идут в порядке файла pytest-randomly
#   --reruns 2 - количество повторов для всех тестов, будет два ререна pytest-rerunfailures
#   -n 3 - количество воркеров по умолчанию pytest-xdist
